services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r medicare_project/requirements
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
