# Generated by Django 5.1.11 on 2025-07-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='disponibilite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.disponibilite'),
        ),
    ]
