# Generated by Django 5.1.11 on 2025-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rendezvous_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='notes_medicales',
            field=models.TextField(blank=True),
        ),
    ]
