# Generated by Django 5.1.11 on 2025-07-14 17:27

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
    ]
