# Generated by Django 5.1.11 on 2025-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
