# Generated by Django 5.1.11 on 2025-07-17 11:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rendezvous_rappel_envoye'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_slot', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medecin')),
            ],
        ),
    ]
